(function(){
  const page=(location.pathname.split('/').pop()||'').toLowerCase();
  const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function inline(anchor,msg,kind='info'){
    let box=anchor.parentElement?.querySelector('.hc-inline-status');
    if(!box){box=document.createElement('div');box.className='hc-inline-status';box.style.cssText='margin-top:12px;font-size:13px;font-weight:700;line-height:1.7;';anchor.insertAdjacentElement('afterend',box)}
    box.style.color=kind==='error'?'#c2413b':kind==='success'?'#228b5b':'var(--ink-soft)';box.textContent=msg;
  }
  async function api(url,opt={}){const r=await fetch(url,{credentials:'include',...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'تعذر تنفيذ العملية');return d;}
  function setChip(btns,active){btns.forEach(b=>{const on=b===active;b.classList.toggle('active',on);b.style.background=on?'var(--navy)':'#fff';b.style.color=on?'#fff':''})}

  async function resources(){
    const input=document.querySelector('.search-hero input');const searchBtn=document.querySelector('.search-hero button');const chips=[...document.querySelectorAll('.filter-chip')];const panel=document.querySelector('.res-row')?.parentElement;let category='الكل';
    async function load(){try{const q=input?.value.trim()||'';const d=await api('/api/resources?q='+encodeURIComponent(q)+'&category='+encodeURIComponent(category));if(!panel)return;panel.innerHTML=d.resources.map(r=>`<div class="res-row"><div class="res-icon">${r.category==='كتب'?'📚':r.category==='تسجيلات'?'🎥':r.category==='أكواد وقوالب'?'💻':r.category==='روابط'?'🔗':'📄'}</div><div style="flex:1"><h6>${esc(r.title)}</h6><span>${esc(r.description)}</span></div><a class="btn btn-ghost sm" href="/api/resources/${encodeURIComponent(r.id)}/download">${r.category==='تسجيلات'?'تنزيل المحتوى':'تحميل'}</a></div>`).join('')||'<div style="padding:25px;text-align:center">لا توجد نتائج مطابقة.</div>';}catch(e){if(searchBtn)inline(searchBtn,e.message,'error')}}
    searchBtn?.addEventListener('click',load);input?.addEventListener('keydown',e=>{if(e.key==='Enter')load()});chips.forEach(c=>c.addEventListener('click',()=>{category=c.textContent.trim();setChip(chips,c);load()}));load();
  }

  async function search(){
    const input=document.querySelector('.page-hero input');const btn=document.querySelector('.page-hero button');const tabs=[...document.querySelectorAll('.tab-btn[data-tab]')];
    const panels=Object.fromEntries([...document.querySelectorAll('[data-panel]')].map(p=>[p.dataset.panel,p]));
    function render(panel,items,fn){if(!panel)return;panel.innerHTML=items.length?items.map(fn).join(''):'<div class="panel">لا توجد نتائج.</div>'}
    async function run(){try{const d=await api('/api/search?q='+encodeURIComponent(input?.value.trim()||''));render(panels.projects,d.projects,x=>`<div class="panel" style="margin-bottom:12px"><h6>${esc(x.name)}</h6><p>${esc(x.description)}</p></div>`);render(panels.articles,d.articles,x=>`<div class="panel" style="margin-bottom:12px"><h6>${esc(x.title)}</h6><p>${esc(x.category)}</p></div>`);render(panels.members,d.members,x=>`<div class="follow-row"><div class="avatar sm">${esc((x.first_name||'')[0]||'ع')}</div><div>${esc(x.first_name+' '+x.last_name)}<span>${esc(x.major||x.university||'عضو')}</span></div></div>`);render(panels.resources,d.resources,x=>`<div class="panel" style="margin-bottom:12px"><h6>${esc(x.title)}</h6><p>${esc(x.description)}</p><a class="btn btn-ghost sm" href="/api/resources/${encodeURIComponent(x.id)}/download">تحميل</a></div>`);const counts={projects:d.projects.length,articles:d.articles.length,members:d.members.length,resources:d.resources.length};tabs.forEach(t=>{const k=t.dataset.tab;if(counts[k]!==undefined)t.textContent=t.textContent.replace(/\s*\(.*\)$/,'')+' ('+counts[k]+')'});}catch(e){inline(btn,e.message,'error')}}
    btn?.addEventListener('click',run);input?.addEventListener('keydown',e=>{if(e.key==='Enter')run()});tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>x.classList.toggle('active',x===t));Object.entries(panels).forEach(([k,p])=>p.classList.toggle('active',k===t.dataset.tab))}));run();
  }

  async function certificates(){
    const grid=document.querySelector('.grid-3');const verifyInput=document.querySelector('input[placeholder*="HASH"]');const verifyBtn=verifyInput?.parentElement?.querySelector('button');
    try{const d=await api('/api/certificates/my');if(grid)grid.innerHTML=d.certificates.length?d.certificates.map(c=>`<div class="cert-card reveal in"><span class="pill good">${esc(c.certificate_type)}</span><h3 style="color:var(--ink);margin-top:14px">${esc(c.title)}</h3><p>صادرة في ${new Date(c.issued_at).toLocaleDateString('ar-SA')}</p><p style="font-size:12px">رمز التحقق: <b>${esc(c.code)}</b></p><div style="display:flex;gap:10px;margin-top:16px"><a class="btn btn-ghost sm" target="_blank" href="/api/certificates/${encodeURIComponent(c.code)}/document">فتح / طباعة PDF</a><a class="btn btn-primary sm" target="_blank" href="https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(location.origin+'/api/certificates/'+c.code+'/document')}">مشاركة على LinkedIn</a></div></div>`).join(''):'<div class="panel" style="grid-column:1/-1;text-align:center">لا توجد شهادات صادرة لك حتى الآن.</div>';}catch(e){if(grid)grid.innerHTML='<div class="panel" style="grid-column:1/-1">تعذر تحميل الشهادات.</div>'}
    verifyBtn?.addEventListener('click',async()=>{try{const code=verifyInput.value.trim();if(!code)throw new Error('أدخل رمز التحقق أولًا');const d=await api('/api/certificates/verify/'+encodeURIComponent(code));let box=verifyBtn.parentElement.querySelector('.verify-result');if(!box){box=document.createElement('div');box.className='verify-result';box.style.marginTop='12px';verifyBtn.parentElement.parentElement.append(box)}box.textContent=`✓ الشهادة صحيحة — ${d.certificate.recipient} — ${d.certificate.title}`;box.style.color='#228b5b'}catch(e){inline(verifyBtn,e.message,'error')}});
  }

  async function tasks(){
    const section=document.querySelector('section.tight .container'); if(!section)return;
    async function load(){try{const d=await api('/api/tasks');const stats={open:d.tasks.filter(x=>x.status==='open').length,in_progress:d.tasks.filter(x=>x.status==='in_progress').length,done:d.tasks.filter(x=>x.status==='done').length};const cards=[...section.querySelectorAll('.grid-4 .stat-card')];if(cards[0])cards[0].querySelector('b').textContent=stats.open;if(cards[1])cards[1].querySelector('b').textContent=stats.in_progress;if(cards[2])cards[2].querySelector('b').textContent=stats.done;let list=document.getElementById('realTasks');if(!list){list=document.createElement('div');list.id='realTasks';section.append(list)}list.innerHTML=d.tasks.length?d.tasks.map(t=>`<div class="panel" style="margin-bottom:16px"><div style="display:flex;justify-content:space-between;gap:10px"><h4>${esc(t.title)}</h4><select class="input task-status" data-id="${esc(t.id)}" style="max-width:160px"><option value="open" ${t.status==='open'?'selected':''}>لم تبدأ</option><option value="in_progress" ${t.status==='in_progress'?'selected':''}>قيد التنفيذ</option><option value="done" ${t.status==='done'?'selected':''}>مكتملة</option></select></div><p style="font-size:13px;color:var(--ink-soft)">المكلّف: ${esc(t.assignee)}</p><button class="btn btn-danger sm task-delete" data-id="${esc(t.id)}">حذف المهمة</button></div>`).join(''):'<div class="panel" style="text-align:center">لا توجد مهام حقيقية محفوظة بعد. أنشئي مهمة من لوحة قائد اللجنة.</div>';list.querySelectorAll('.task-status').forEach(x=>x.addEventListener('change',async()=>{try{await api('/api/tasks/'+x.dataset.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:x.value})})}catch(e){inline(x,e.message,'error')}}));list.querySelectorAll('.task-delete').forEach(x=>x.addEventListener('click',async()=>{try{await api('/api/tasks/'+x.dataset.id,{method:'DELETE'});load()}catch(e){inline(x,e.message,'error')}}));}catch(e){}}load();
  }

  async function dashboard(){
    const tabs=[...document.querySelectorAll('.role-tab')];const panels=[...document.querySelectorAll('[data-role-panel]')];tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>x.classList.toggle('active',x===t));panels.forEach(p=>p.style.display=p.dataset.rolePanel===t.dataset.role?'block':'none')}));
    const lead=[...document.querySelectorAll('[data-role-panel="lead"] button')].find(b=>b.textContent.includes('إنشاء المهمة'));
    lead?.addEventListener('click',async()=>{const panel=lead.closest('[data-role-panel]');const inputs=panel.querySelectorAll('input,select');try{await api('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:inputs[0].value,assignee:inputs[1].value})});inputs[0].value='';inline(lead,'تم إنشاء المهمة وحفظها.','success')}catch(e){inline(lead,e.message,'error')}});
    const issue=[...document.querySelectorAll('[data-role-panel="instructor"] button')].find(b=>b.textContent.trim()==='إصدار');
    issue?.addEventListener('click',async()=>{const input=issue.parentElement.querySelector('input');try{const d=await api('/api/certificates/issue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipient:input.value,title:'شهادة مشاركة من نادي هاش'})});inline(issue,'تم إصدار الشهادة برمز: '+d.code,'success')}catch(e){inline(issue,e.message,'error')}});
    const tbody=document.querySelector('[data-role-panel="admin"] tbody');
    async function apps(){if(!tbody)return;try{const d=await api('/api/admin/membership-applications');tbody.innerHTML=d.applications.length?d.applications.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.major||a.application.major||'—')}</td><td>${new Date(a.submittedAt).toLocaleDateString('ar-SA')}</td><td><span class="pill warn">قيد المراجعة</span></td><td><button class="btn sm btn-primary accept-app" data-id="${esc(a.id)}">قبول</button></td></tr>`).join(''):'<tr><td colspan="5">لا توجد طلبات معلقة.</td></tr>';tbody.querySelectorAll('.accept-app').forEach(b=>b.addEventListener('click',async()=>{try{await api('/api/admin/membership/'+b.dataset.id+'/accept',{method:'POST'});apps()}catch(e){inline(b,e.message,'error')}}));}catch(e){tbody.innerHTML='<tr><td colspan="5">'+esc(e.message)+'</td></tr>'}}apps();
  }

  async function stats(){try{const d=await api('/api/stats');const cards=[...document.querySelectorAll('.stat-card b')];const vals=[d.stats.users,d.stats.posts,d.stats.projects,d.stats.eventRegistrations,d.stats.courseEnrollments];cards.slice(0,vals.length).forEach((x,i)=>x.textContent=vals[i]);}catch(e){}}
  async function achievements(){try{const d=await api('/api/achievements/leaderboard');const board=document.querySelector('.leaderboard, .panel');if(!board)return;let host=document.getElementById('realLeaderboard');if(!host){host=document.createElement('div');host.id='realLeaderboard';board.parentElement.append(host)}host.innerHTML='<div class="panel">'+(d.leaderboard.length?d.leaderboard.map(x=>`<div class="info-row"><span>#${x.rank} ${esc(x.name)}</span><b>${x.points} نقطة</b></div>`).join(''):'لا توجد بيانات كافية بعد.')+'</div>'}catch(e){}}

  document.addEventListener('DOMContentLoaded',()=>{if(page==='resources.html')resources();if(page==='search.html')search();if(page==='certificates.html')certificates();if(page==='my-tasks.html')tasks();if(page==='dashboards.html')dashboard();if(page==='stats.html')stats();if(page==='achievements.html')achievements();});
})();
