/* Phase 12 — real one-to-one messaging with database-backed recipients. */
(function(){
  if((location.pathname.split('/').pop()||'').toLowerCase()!=='messages.html')return;
  const api=async(url,opt={})=>{const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'تعذر تنفيذ العملية');return d;};
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function status(t,ok=true){let e=document.getElementById('pageActionStatus');if(!e){e=document.createElement('div');e.id='pageActionStatus';e.style.cssText='margin:12px auto;max-width:1100px;padding:12px 16px;border-radius:10px';(document.querySelector('.chat-shell')||document.body).before(e)}e.textContent=t;e.style.background=ok?'#edf8f0':'#fff1f1';e.style.color=ok?'#176b3a':'#9c2424'}
  document.addEventListener('DOMContentLoaded',async()=>{
    const list=document.querySelector('.chat-list'),body=document.querySelector('.chat-body'),input=document.querySelector('.chat-input input'),send=document.querySelector('.chat-input button'),peerName=document.getElementById('chatPeerName'); if(!list||!body||!input||!send)return;
    let peerId='';
    const load=async()=>{if(!peerId){body.textContent='اختاري عضوًا لبدء محادثة.';return}const d=await api('/api/messages?with='+encodeURIComponent(peerId));body.innerHTML=d.messages.length?d.messages.map(m=>`<div class="bubble ${m.mine?'out':'in'}">${esc(m.body)}</div>`).join(''):'<div style="padding:20px;text-align:center;color:var(--ink-soft)">لا توجد رسائل بعد. ابدئي المحادثة.</div>';body.scrollTop=body.scrollHeight};
    try{const d=await api('/api/messages/contacts');list.innerHTML='';d.contacts.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.className='chat-list-item'+(i===0?' active':'');b.style.cssText='width:100%;border:0;background:transparent;text-align:inherit';b.innerHTML=`<div class="avatar sm">${esc(c.name.split(/\s+/).map(x=>x[0]).join('.').slice(0,3))}</div><div><b style="font-size:13.5px">${esc(c.name)}</b><br><span style="font-size:12px;color:var(--ink-soft)">${esc(c.major||c.email)}</span></div>`;b.addEventListener('click',async()=>{list.querySelectorAll('.chat-list-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');peerId=c.id;if(peerName)peerName.textContent=c.name;await load()});list.appendChild(b);if(i===0){peerId=c.id;if(peerName)peerName.textContent=c.name}});if(!d.contacts.length)list.innerHTML='<div style="padding:18px;color:var(--ink-soft)">لا يوجد أعضاء آخرون بعد.</div>';await load()}catch(e){status(e.message,false);return}
    const submit=async()=>{const text=input.value.trim();if(!text||!peerId)return;send.disabled=true;try{await api('/api/messages',{method:'POST',body:JSON.stringify({recipientId:peerId,body:text})});input.value='';await load()}catch(e){status(e.message,false)}finally{send.disabled=false}};send.addEventListener('click',submit);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();submit()}})
  });
})();
