/* Phase 16 — live tasks, course enrollment state, and admin applications. */
(function(){
  const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=async(url,opt={})=>{const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch(e){} if(!r.ok)throw new Error(d.error||'تعذّر تنفيذ العملية');return d};
  const statusLabel={open:'لم تبدأ',in_progress:'قيد التنفيذ',done:'مكتملة',cancelled:'ملغاة'};
  function statusClass(s){return s==='done'?'good':s==='in_progress'?'warn':s==='cancelled'?'danger':''}
  function message(el,text,ok){let m=el.querySelector('.hc-phase16-msg');if(!m){m=document.createElement('div');m.className='hc-phase16-msg';m.style.cssText='margin-top:12px;font-size:13px;font-weight:700';el.prepend(m)}m.textContent=text;m.style.color=ok?'#16784a':'#b42318'}
  async function initTasks(){
    const section=document.querySelector('section.tight .container'); if(!section)return;
    section.innerHTML='<div class="panel" id="taskApp"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><h3 style="color:var(--ink)">مهامي الحقيقية</h3><p style="color:var(--ink-soft);font-size:13px">هذه المهام محفوظة في قاعدة البيانات.</p></div></div><form id="taskCreate" style="display:grid;grid-template-columns:1fr 1fr auto;gap:10px;margin:18px 0"><input class="input" name="title" placeholder="عنوان المهمة" required><input class="input" name="assignee" placeholder="المكلّف بالمهمة" required><button class="btn btn-primary" type="submit">إضافة مهمة</button></form><div id="taskStats" class="grid-4" style="margin-bottom:20px"></div><div id="taskList"></div></div>';
    const app=section.querySelector('#taskApp'), list=section.querySelector('#taskList'), stats=section.querySelector('#taskStats');
    async function load(){try{const d=await api('/api/tasks');const tasks=d.tasks||[];const counts={open:0,in_progress:0,done:0,cancelled:0};tasks.forEach(t=>counts[t.status]=(counts[t.status]||0)+1);stats.innerHTML=`<div class="stat-card"><b>${counts.open}</b><span>لم تبدأ</span></div><div class="stat-card"><b>${counts.in_progress}</b><span>قيد التنفيذ</span></div><div class="stat-card"><b>${counts.done}</b><span>مكتملة</span></div><div class="stat-card"><b>${tasks.length}</b><span>إجمالي المهام</span></div>`;list.innerHTML=tasks.length?tasks.map(t=>`<div class="panel" style="margin-bottom:14px" data-id="${esc(t.id)}"><div style="display:flex;justify-content:space-between;gap:10px;align-items:start"><div><h4 style="color:var(--ink)">${esc(t.title)}</h4><p style="font-size:13px;color:var(--ink-soft);margin-top:6px">المكلّف: ${esc(t.assignee)}</p></div><span class="pill ${statusClass(t.status)}">${statusLabel[t.status]||t.status}</span></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:14px"><select class="input task-status" style="max-width:170px"><option value="open" ${t.status==='open'?'selected':''}>لم تبدأ</option><option value="in_progress" ${t.status==='in_progress'?'selected':''}>قيد التنفيذ</option><option value="done" ${t.status==='done'?'selected':''}>مكتملة</option></select><button class="btn btn-ghost sm task-comments">التعليقات</button><button class="btn btn-ghost sm task-delete">حذف</button></div><div class="task-comments-box" style="display:none;margin-top:14px"></div></div>`).join(''):'<p style="color:var(--ink-soft);padding:20px">لا توجد مهام حتى الآن. أضيفي أول مهمة من النموذج أعلاه.</p>'}catch(e){message(app,e.message,false)}}
    section.querySelector('#taskCreate').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/tasks',{method:'POST',body:JSON.stringify({title:f.get('title'),assignee:f.get('assignee')})});e.currentTarget.reset();message(app,'تم إنشاء المهمة وحفظها.',true);load()}catch(x){message(app,x.message,false)}});
    list.addEventListener('change',async e=>{if(!e.target.matches('.task-status'))return;const row=e.target.closest('[data-id]');try{await api('/api/tasks/'+encodeURIComponent(row.dataset.id),{method:'PATCH',body:JSON.stringify({status:e.target.value})});load()}catch(x){message(app,x.message,false)}});
    list.addEventListener('click',async e=>{const row=e.target.closest('[data-id]');if(!row)return;const id=row.dataset.id;if(e.target.closest('.task-delete')){try{await api('/api/tasks/'+encodeURIComponent(id),{method:'DELETE'});message(app,'تم حذف المهمة.',true);load()}catch(x){message(app,x.message,false)}} if(e.target.closest('.task-comments')){const box=row.querySelector('.task-comments-box');box.style.display=box.style.display==='none'?'block':'none';if(box.style.display==='none')return;try{const d=await api('/api/tasks/'+encodeURIComponent(id)+'/comments');box.innerHTML=`<div class="comment-list">${(d.comments||[]).map(c=>`<p style="font-size:13px;margin:8px 0"><b>${esc(c.author)}:</b> ${esc(c.body)}</p>`).join('')||'<p style="font-size:13px;color:var(--ink-soft)">لا توجد تعليقات.</p>'}</div><form class="comment-form" style="display:flex;gap:8px;margin-top:10px"><input class="input" name="body" placeholder="أضيفي تعليقًا" required><button class="btn btn-primary sm">إرسال</button></form>`;box.querySelector('form').addEventListener('submit',async ev=>{ev.preventDefault();const body=new FormData(ev.currentTarget).get('body');try{await api('/api/tasks/'+encodeURIComponent(id)+'/comments',{method:'POST',body:JSON.stringify({body})});e.target.closest('.task-comments').click()}catch(x){message(app,x.message,false)}})}catch(x){message(app,x.message,false)}}});
    load();
  }
  async function initCourses(){
    const cards=[...document.querySelectorAll('.tab-panel[data-panel="courses"] article.card')];if(!cards.length)return;const ids=['cloud-basics','modern-frontend','info-security','ui-basics','devops','machine-learning'];cards.forEach((card,i)=>{const foot=card.querySelector('.card-foot');if(!foot)return;foot.style.cursor='pointer';foot.dataset.courseId=ids[i]||('course-'+i);foot.addEventListener('click',async()=>{try{await api('/api/courses/'+encodeURIComponent(foot.dataset.courseId)+'/enroll',{method:'POST'});const a=foot.querySelector('span:first-child');if(a)a.textContent='تم التسجيل ✓';message(card,'تم تسجيلك في الدورة وحفظ التسجيل في حسابك.',true)}catch(e){if(e.message.includes('تسجيل الدخول'))location.href='auth.html';else message(card,e.message,false)}})});api('/api/courses/my').then(d=>{const set=new Set((d.courses||[]).map(x=>x.id));cards.forEach((card,i)=>{const foot=card.querySelector('.card-foot');if(foot&&set.has(foot.dataset.courseId)){const a=foot.querySelector('span:first-child');if(a)a.textContent='تم التسجيل ✓'}})}).catch(()=>{});
  }
  async function initDashboard(){
    const tab=[...document.querySelectorAll('.role-tab')].find(x=>x.dataset.role==='admin'); if(!tab)return;const panel=document.querySelector('[data-role-panel="admin"],#admin-panel');
    // Existing admin tab is populated after it becomes active; replace pending rows with live applications.
    tab.addEventListener('click',async()=>{try{const d=await api('/api/admin/membership-applications');const rows=[...document.querySelectorAll('table tbody')][0];if(!rows)return;rows.innerHTML=(d.applications||[]).map(a=>`<tr data-user-id="${esc(a.id)}"><td>${esc(a.name)}</td><td>${esc(a.major||'—')}</td><td>${new Date(a.submittedAt).toLocaleDateString('ar-SA')}</td><td><span class="pill warn">قيد المراجعة</span></td><td><button class="btn sm btn-primary accept-member">قبول</button></td></tr>`).join('')||'<tr><td colspan="5">لا توجد طلبات معلقة.</td></tr>';rows.addEventListener('click',async e=>{const b=e.target.closest('.accept-member');if(!b)return;const r=b.closest('tr');try{await api('/api/admin/membership/'+encodeURIComponent(r.dataset.userId)+'/accept',{method:'POST'});r.remove()}catch(x){message(document.querySelector('.dash-panel')||document.body,x.message,false)}})}catch(e){/* account may not be admin; do not fake data */}});
  }
  document.addEventListener('DOMContentLoaded',()=>{if(page==='my-tasks.html')initTasks();if(page==='courses.html')initCourses();if(page==='dashboards.html')initDashboard();});
})();
